---
title: "MY472: Exercise 1"
author: "LSE Candidate Number: 201420265"
date: "Autumn Term 2024"
output: html_document
---

```{r setup, include=FALSE} 
# this chunk contains code that sets global options for the entire .Rmd. 
# we use include=FALSE to suppress it from the top of the document, but it will still appear in the appendix. 

knitr::opts_chunk$set(echo = FALSE) # actually set the global chunk options. 
# we set echo=FALSE to suppress code such that it by default does not appear throughout the document. 
# note: this is different from .Rmd default
```

```{r echo_example, echo=TRUE}
# Single function with 'data' argument

# Leverage built-in mtcars dataset
d <- mtcars$cyl

# Function 'fn' doubles the cyl (cylinder count) column of mtcars which is stored in 'data'
fn <- function(data){

  return(2*data)
  
}

fn(d)

# Function 'fn2' triples the cyl (cylinder count) column of mtcars which is stored in 'data'
fn2 <- function(data_new){

  return(3*data_new)
  
}

fn2(d)
```




